## Concatenating DataFrames from a dict

Instead of using the `keys=[]` argument to `pd.concat()`, we can create a dictionary mapping index labels to input DataFrames. This works just as well as using the `keys` argument, but it's a little safer and more explicit, because with a dictionary the mapping between labels and data is easy to verify. Using separate lists of DataFrames and keys relies on ensuring that the order of items is the same in both lists.

In [24]:
sess_dict = {'session 1':sess_1, 'session 2':sess_2}

sess_12 = pd.concat(sess_dict)

sess_12

                    rt
          trial
session 1 0      0.988
          1      0.753
          2      0.949
          3      0.824
          4      0.262
          5      0.803
          6      0.376
          7      0.496
          8      0.235
          9      0.336
          10     0.645
session 2 0      0.718
          1      0.851
          2      0.747
          3      0.520
          4      0.991
          5      0.004
          6      0.547
          7      0.883
          8      0.841
          9      0.195
          10     0.828